
CREATE TABLE SURVEY.STG_DATA (
	EMAIL VARCHAR(255),
	SURVEYID VARCHAR(20),
	ANSWERID VARCHAR(20),
	REPORT VARCHAR(50),
	SURVEYSTARTED TIMESTAMP_TZ(9),
	SURVEYENDED TIMESTAMP_TZ(9),
	SURVEYLENGTH NUMBER(38,0),
	LANGUAGE VARCHAR(255),
	CALLSTARTTIME VARCHAR(255),
	CONTACTGUID VARCHAR(255),
	CALLENDTIME VARCHAR(255),
	SERVICEQUEUENAME VARCHAR(255),
	WAITINGSTARTTIME VARCHAR(255),
	NAMEOFAGENT VARCHAR(255),
	QUESTION1 VARCHAR(10),
	QUESTION2 NUMBER(38,0),
	QUESTION3 NUMBER(38,0),
	OPENTEXT VARCHAR(16777216),
	QUESTION4ICON VARCHAR(255),
	REASONFORSCORE VARCHAR(255)
);
GRANT TRUNCATE ON TABLE SURVEY.STG_DATA TO ROLE SYSADMIN;
GRANT REFERENCES ON TABLE SURVEY.STG_DATA TO ROLE SYSADMIN;
GRANT DELETE ON TABLE SURVEY.STG_DATA TO ROLE SYSADMIN;
GRANT INSERT ON TABLE SURVEY.STG_DATA TO ROLE SYSADMIN;
GRANT SELECT ON TABLE SURVEY.STG_DATA TO ROLE SYSADMIN;
GRANT REBUILD ON TABLE SURVEY.STG_DATA TO ROLE SYSADMIN;
GRANT UPDATE ON TABLE SURVEY.STG_DATA TO ROLE SYSADMIN;
