CREATE SCHEMA SURVEY

GRANT PRIVLIEGE CREATE PROCEDURE ON  SCHEMA SURVEY TO ROLE LOOKER_SURVEYPAL;
GRANT PRIVLIEGE OWNERSHIP ON  SCHEMA SURVEY TO ROLE LOOKER_SURVEYPAL;
GRANT PRIVLIEGE CREATE STAGE ON  SCHEMA SURVEY TO ROLE SYSADMIN;
GRANT PRIVLIEGE CREATE TABLE ON  SCHEMA SURVEY TO ROLE SYSADMIN;
GRANT PRIVLIEGE CREATE VIEW ON  SCHEMA SURVEY TO ROLE SYSADMIN;
GRANT PRIVLIEGE USAGE ON  SCHEMA SURVEY TO ROLE SYSADMIN;