
CREATE TABLE KAITO.AGENT (
	NAME VARCHAR(255),
	EMAIL VARCHAR(255),
	TEAM_ID VARCHAR(5),
	RESPONSES NUMBER(18,0),
	RESOLVED_CALLS NUMBER(13,0),
	STARTED_DATE DATE,
	PASSIVE NUMBER(13,0),
	PROMOTERS NUMBER(13,0),
	DETRACTORS NUMBER(13,0),
	NEXT_LEVEL_STATUS VARCHAR(23),
	NEXT_MILESTONE NUMBER(18,5)
);
GRANT DELETE ON TABLE KAITO.AGENT TO ROLE SYSADMIN;
GRANT REFERENCES ON TABLE KAITO.AGENT TO ROLE SYSADMIN;
GRANT SELECT ON TABLE KAITO.AGENT TO ROLE SYSADMIN;
GRANT UPDATE ON TABLE KAITO.AGENT TO ROLE SYSADMIN;
GRANT REBUILD ON TABLE KAITO.AGENT TO ROLE SYSADMIN;
GRANT INSERT ON TABLE KAITO.AGENT TO ROLE SYSADMIN;
GRANT TRUNCATE ON TABLE KAITO.AGENT TO ROLE SYSADMIN;
