CREATE SCHEMA KAITO;

GRANT USAGE ON  SCHEMA KAITO TO ROLE LOOKER_SURVEYPAL;
GRANT USAGE ON  SCHEMA KAITO TO ROLE SYSADMIN;
GRANT CREATE STAGE ON  SCHEMA KAITO TO ROLE SYSADMIN;
GRANT CREATE TABLE ON  SCHEMA KAITO TO ROLE SYSADMIN;
GRANT CREATE VIEW ON  SCHEMA KAITO TO ROLE SYSADMIN;