

CREATE OR REPLACE VIEW  KAITO.VIEW_NLP_DETAILS AS 
SELECT DISTINCT
    S.ANSWERID AS ANSWERID,
    --SPLIT(ADJECTIVES_NOUNS,',')
    TO_VARCHAR(TRIM(C.value)) AS ADJECTIVES_NOUNS,
    TO_VARCHAR(TRIM(K.value)) AS KEYWORDS,
    COUNT(*) AS COUNT
FROM
    SURVEYS_NLP S,
    LATERAL FLATTEN(input=>SPLIT(ADJECTIVES_NOUNS,',')) C,
    LATERAL FLATTEN(input=>SPLIT(KEYWORDS,',')) K
//   ATERAL FLATTEN(input=>split(children, ',')) C;

//WHERE
//	((S."ADJECTIVES_NOUNS") = 'pitkä jonotus#aika, epä#selvä aika#taulu, turha info, yksinkertainen tieto')
GROUP BY 
    1,2,3;

GRANT OWNERSHIP ON TABLE KAITO.VIEW_NLP_DETAILS TO ROLE SYSADMIN;
GRANT SELECT ON TABLE KAITO.VIEW_NLP_DETAILS TO ROLE LOOKER_SURVEYPAL;
