

CREATE OR REPLACE VIEW  SURVEY.VW_NLP_ATTRIBUTION  AS 
SELECT DISTINCT
    S.ANSWERID AS ANSWERID,
    --SPLIT(ADJECTIVES_NOUNS,',')
    TO_VARCHAR(TRIM(C.value)) AS ADJECTIVES_NOUNS,
    TO_VARCHAR(TRIM(K.value)) AS KEYWORDS,
    COUNT(*) AS COUNT
FROM
    SURVEYS_NLP S,
    LATERAL FLATTEN(input=>SPLIT(ADJECTIVES_NOUNS,',')) C,
    LATERAL FLATTEN(input=>SPLIT(KEYWORDS,',')) K
//   ATERAL FLATTEN(input=>split(children, ',')) C;

//WHERE
//	((S."ADJECTIVES_NOUNS") = 'pitkä jonotus#aika, epä#selvä aika#taulu, turha info, yksinkertainen tieto')
GROUP BY 
    1,2,3;

GRANT REBUILD ON TABLE SURVEY.VW_NLP_ATTRIBUTION TO ROLE SYSADMIN;
GRANT UPDATE ON TABLE SURVEY.VW_NLP_ATTRIBUTION TO ROLE SYSADMIN;
GRANT DELETE ON TABLE SURVEY.VW_NLP_ATTRIBUTION TO ROLE SYSADMIN;
GRANT REFERENCES ON TABLE SURVEY.VW_NLP_ATTRIBUTION TO ROLE SYSADMIN;
GRANT INSERT ON TABLE SURVEY.VW_NLP_ATTRIBUTION TO ROLE SYSADMIN;
GRANT SELECT ON TABLE SURVEY.VW_NLP_ATTRIBUTION TO ROLE SYSADMIN;
GRANT TRUNCATE ON TABLE SURVEY.VW_NLP_ATTRIBUTION TO ROLE SYSADMIN;
