
CREATE TABLE SURVEY.SURVEYS_NLP (
	SURVEYID VARIANT,
	ANSWERID VARCHAR(16777216),
	SERVICEQUEUENAME VARCHAR(16777216),
	NAMEOFAGENT VARIANT,
	QUESTION1 VARCHAR(16777216),
	QUESTION2 VARIANT,
	QUESTION3 VARIANT,
	OPENTEXT VARIANT,
	QUESTION4ICON VARCHAR(16777216),
	NOUNS VARCHAR(16777216),
	VERBS VARCHAR(16777216),
	ADJECTIVES VARCHAR(16777216),
	ADJECTIVES_NOUNS VARCHAR(16777216),
	KEYWORDS VARCHAR(16777216),
	PCA VARCHAR(16777216),
	KMEANS VARIANT
);
GRANT REFERENCES ON TABLE SURVEY.SURVEYS_NLP TO ROLE SYSADMIN;
GRANT TRUNCATE ON TABLE SURVEY.SURVEYS_NLP TO ROLE SYSADMIN;
GRANT INSERT ON TABLE SURVEY.SURVEYS_NLP TO ROLE SYSADMIN;
GRANT DELETE ON TABLE SURVEY.SURVEYS_NLP TO ROLE SYSADMIN;
GRANT UPDATE ON TABLE SURVEY.SURVEYS_NLP TO ROLE SYSADMIN;
GRANT SELECT ON TABLE SURVEY.SURVEYS_NLP TO ROLE LOOKER_SURVEYPAL;
GRANT REBUILD ON TABLE SURVEY.SURVEYS_NLP TO ROLE SYSADMIN;
GRANT SELECT ON TABLE SURVEY.SURVEYS_NLP TO ROLE SYSADMIN;
